from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

from app.db.d1_bootstrap import (
    DATA_TABLES,
    FORMAT_VERSION,
    MANIFEST_TABLES,
    OPERATIONAL_TABLES,
    REFERENCE_TABLES,
    build_manifest,
    compare_manifest,
    load_manifest_file,
    resolve_d1_local_database,
    verify_database,
    write_bootstrap_package as _write_base_package,
)


def _sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bytes):
        return "X'" + value.hex() + "'"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _reference_metadata_sql(database_path: str | Path) -> str:
    """Preserve metadata fields generated by SQLite migration defaults.

    D1 reference migrations intentionally create the same stable source, instrument and
    curated Bemobi identities, but DEFAULT timestamps naturally reflect D1 migration time.
    Historical parity preserves the source snapshot at the logical row level, so the
    bootstrap updates only migration-generated metadata after the reference seeds have run.
    IDs and semantic fields remain validated by the manifest.
    """
    path = Path(database_path).resolve()
    connection = sqlite3.connect(f"file:{path.as_posix()}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    try:
        lines = ["", "-- Preserve reference-row migration metadata from the SQLite snapshot."]
        for row in connection.execute(
            "SELECT id, created_at, updated_at FROM sources ORDER BY id"
        ):
            lines.append(
                "UPDATE \"sources\" "
                f"SET \"created_at\" = {_sql_literal(row['created_at'])}, "
                f"\"updated_at\" = {_sql_literal(row['updated_at'])} "
                f"WHERE \"id\" = {_sql_literal(row['id'])};"
            )
        for row in connection.execute(
            "SELECT id, created_at FROM instruments ORDER BY id"
        ):
            lines.append(
                "UPDATE \"instruments\" "
                f"SET \"created_at\" = {_sql_literal(row['created_at'])} "
                f"WHERE \"id\" = {_sql_literal(row['id'])};"
            )
        for row in connection.execute(
            "SELECT id, created_at, updated_at FROM bemobi_investor_facts ORDER BY id"
        ):
            lines.append(
                "UPDATE \"bemobi_investor_facts\" "
                f"SET \"created_at\" = {_sql_literal(row['created_at'])}, "
                f"\"updated_at\" = {_sql_literal(row['updated_at'])} "
                f"WHERE \"id\" = {_sql_literal(row['id'])};"
            )
        for row in connection.execute(
            "SELECT id, created_at FROM bemobi_forward_consensus_snapshots ORDER BY id"
        ):
            lines.append(
                "UPDATE \"bemobi_forward_consensus_snapshots\" "
                f"SET \"created_at\" = {_sql_literal(row['created_at'])} "
                f"WHERE \"id\" = {_sql_literal(row['id'])};"
            )
        for row in connection.execute(
            "SELECT id, created_at, updated_at FROM bemobi_consensus_events ORDER BY id"
        ):
            lines.append(
                "UPDATE \"bemobi_consensus_events\" "
                f"SET \"created_at\" = {_sql_literal(row['created_at'])}, "
                f"\"updated_at\" = {_sql_literal(row['updated_at'])} "
                f"WHERE \"id\" = {_sql_literal(row['id'])};"
            )
        return "\n".join(lines) + "\n"
    finally:
        connection.close()


def write_bootstrap_package(
    database_path: str | Path,
    sql_path: str | Path,
    manifest_path: str | Path,
) -> dict[str, Any]:
    manifest = _write_base_package(database_path, sql_path, manifest_path)
    output = Path(sql_path)
    with output.open("a", encoding="utf-8", newline="") as handle:
        handle.write(_reference_metadata_sql(database_path))
    return manifest


__all__ = [
    "DATA_TABLES",
    "FORMAT_VERSION",
    "MANIFEST_TABLES",
    "OPERATIONAL_TABLES",
    "REFERENCE_TABLES",
    "build_manifest",
    "compare_manifest",
    "load_manifest_file",
    "resolve_d1_local_database",
    "verify_database",
    "write_bootstrap_package",
]
